project_directory: project
virtual_projects: {}
console_port: null
realtime:
  transport: auto
  broker: auto
  autostart: true
  keepalive: false
  uds_socket_path: null
  topics:
    project_events: projects/{project}/events
overlay:
  enabled: true
  ttl_s: 86400
hooks:
  enabled: true
  run_in_beads_mode: true
  default_timeout_ms: 5000
  before: {}
  after: {}
project_key: KDATAP
hierarchy:
- initiative
- epic
- task
- sub-task
types:
- bug
- story
- chore
workflows:
  default:
    backlog:
    - open
    - closed
    open:
    - in_progress
    - closed
    - backlog
    in_progress:
    - open
    - blocked
    - closed
    blocked:
    - in_progress
    - closed
    closed:
    - open
  epic:
    open:
    - in_progress
    - closed
    in_progress:
    - open
    - closed
    closed:
    - open
initial_status: open
priorities:
  0:
    name: critical
    color: red
  1:
    name: high
    color: bright_red
  2:
    name: medium
    color: yellow
  3:
    name: low
    color: blue
  4:
    name: trivial
    color: white
default_priority: 2
assignee: null
time_zone: null
categories:
- name: To do
  color: grey
- name: In progress
  color: blue
- name: Done
  color: green
sort_order: {}
statuses:
- key: backlog
  name: Backlog
  category: To do
  collapsed: true
- key: open
  name: Discovery
  category: To do
  collapsed: false
- key: in_progress
  name: In Progress
  category: In progress
  collapsed: false
- key: blocked
  name: Blocked
  category: In progress
  collapsed: true
- key: closed
  name: Done
  category: Done
  collapsed: true
transition_labels:
  default:
    backlog:
      open: Start discovery
      closed: Drop
    open:
      in_progress: Start work
      closed: Drop
      backlog: Back to backlog
    in_progress:
      open: Pause
      blocked: Block
      closed: Complete
    blocked:
      in_progress: Unblock
      closed: Drop
    closed:
      open: Reopen
  epic:
    open:
      in_progress: Start
      closed: Complete
    in_progress:
      open: Pause
      closed: Complete
    closed:
      open: Reopen
type_colors:
  initiative: bright_blue
  epic: magenta
  task: blue
  sub-task: bright_cyan
  bug: red
  story: yellow
  chore: green
  event: bright_blue
beads_compatibility: false
wiki_directory: null
github_security: null
