packages:
  - "."

allowBuilds:
  "@dataparade/scanner@https://codeload.github.com/DataParade-io/scanner/tar.gz/e0dcef681c88f5b78ed12139308e5193c2a783f6": true
  "@dataparade/scanner@https://codeload.github.com/DataParade-io/scanner/tar.gz/9f2f5fc9d361ebbe3a21911b1ee53b4c9f34ba88": true
